project:
  type: book
  title: "end-training"
  
book:
  title: "Utholdenhetstrening"
  author: "Sjur Fortun Øfsteng"
  date: "last-modified"
  search: true
  repo-url: https://github.com/sjurjo/mit-end
  repo-branch: master
  chapters:
  - index.qmd
  - 01-intro.qmd
  
  
brand: _brand.yml
#bibliography: 